project_name: RectangleWin

builds:
  - id: windows_build
    goos:
      - windows
    goarch:
      - 386
      - amd64
    ldflags:
      - -H=windowsgui
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    builds:
      - windows_build
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Arch }}-v{{ .Version }}"
    replacements:
      386: x86
      amd64: x64