name: Release
on:
  workflow_dispatch: 

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: | 
        go env -w GOOS=windows
        go build -ldflags -H=windowsgui .
        mkdir build/
        move RectangleWin.exe build/RectangleWin.exe
        move config.yaml build/RectangleWin.exe

    - name: Create GitHub Release
      uses: fnkr/github-action-ghr@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: build/
          GHR_COMPRESS: zip
